# Generated by Django 4.2.16 on 2025-09-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
