# Generated by Django 4.2.16 on 2025-10-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewHistory',
        ),
    ]
